# NAME: Anh Mac
# EMAIL: anhmvc@gmail.com
# UID: 905111606

default:
	tar -czvf lab4a-905111606.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png README Makefile

clean:
	rm -f *.tar.gz
