# NAME: Anh Mac
# EMAIL: anhmvc@gmail.com
# ID: 905111606

lab1a: lab1a.c
	gcc -Wall -Wextra -o lab1a lab1a.c

clean:
	rm -f lab1a *.tar.gz

dist:
	tar -czvf lab1a-905111606.tar.gz lab1a.c Makefile README
