# NAME: Anh Mac,William Chen
# EMAIL: anhmvc@gmail.com,billy.lj.chen@gmail.com
# UID: 905111606,405131881

default:
	gcc -Wall -Wextra lab3a.c -o lab3a

dist:
	tar -cvzf lab3a-905111606.tar.gz lab3a.c Makefile README ext2_fs.h

clean:
	rm -f *.tar.gz lab3a